version: 2.1
# third party orbs
orbs:
  cypress: cypress-io/cypress@1.19.1
workflows:
  build:
    jobs:
      - cypress/install:
          build: "npm run build"
      - cypress/run:
          record: true
          parallel: true
          parallelism: 10
  test:
    jobs:
      - run:
          command: "npm run test-headless"