version: 2.1
# third party orbs
orbs:
  cypress: cypress-io/cypress@1.19.1
workflows:
  build:
    jobs:
      - cypress/install:
           build: "yarn run build"
      - cypress/run:
           record: true
           parallel: true
           parallelism: 10
