version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    executor:
      name: node@10.13.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - node/with-cache:
          steps:
            - run: yarn install
            - save_cache:
                key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
                paths:
                  - ~/.npm
                  - ~/.cache
            - run: yarn run test-headless
workflows:
  build-and-test:
    jobs:
      - build-and-test
