version: 2

jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    steps:
      - checkout
      - run:
          name: install
          command: "npm install"
      - restore_cache:
          key:
            - dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-{{ .Branch }}
            - dependency-cache
      - run:
          name: build
          command: "npm build"

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache
      - run:
          name: test
          command: "npm test"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build